const europeanCountries = [
    {'': 'Choose a country'},
    { 'albania': 'Albania' },
    { 'andorra': 'Andorra' },
    { 'armenia': 'Armenia' },
    { 'austria': 'Austria' },
    { 'azerbaijan': 'Azerbaijan' },
    { 'belarus': 'Belarus' },
    { 'belgium': 'Belgium' },
    { 'bosnia': 'Bosnia and Herzegovina' },
    { 'bulgaria': 'Bulgaria' },
    { 'croatia': 'Croatia' },
    { 'cyprus': 'Cyprus' },
    { 'czechia': 'Czech Republic' },
    { 'denmark': 'Denmark' },
    { 'estonia': 'Estonia' },
    { 'finland': 'Finland' },
    { 'france': 'France' },
    { 'georgia': 'Georgia' },
    { 'germany': 'Germany' },
    { 'greece': 'Greece' },
    { 'hungary': 'Hungary' },
    { 'iceland': 'Iceland' },
    { 'ireland': 'Ireland' },
    { 'italy': 'Italy' },
    { 'kosovo': 'Kosovo' },
    { 'latvia': 'Latvia' },
    { 'liechtenstein': 'Liechtenstein' },
    { 'lithuania': 'Lithuania' },
    { 'luxembourg': 'Luxembourg' },
    { 'malta': 'Malta' },
    { 'moldova': 'Moldova' },
    { 'monaco': 'Monaco' },
    { 'montenegro': 'Montenegro' },
    { 'netherlands': 'Netherlands' },
    { 'north macedonia': 'North Macedonia' },
    { 'norway': 'Norway' },
    { 'poland': 'Poland' },
    { 'portugal': 'Portugal' },
    { 'romania': 'Romania' },
    { 'russia': 'Russia' },
    { 'san marino': 'San Marino' },
    { 'serbia': 'Serbia' },
    { 'slovakia': 'Slovakia' },
    { 'slovenia': 'Slovenia' },
    { 'spain': 'Spain' },
    { 'sweden': 'Sweden' },
    { 'switzerland': 'Switzerland' },
    { 'ukraine': 'Ukraine' },
    { 'united kingdom': 'United Kingdom' },
    { 'vatican city': 'Vatican City' },
];

module.exports = europeanCountries;